# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29dedfe257f84ce5d15de2ca7d78152d0bca8cbd754a1220587dd68253761ef44bfd8eda42b07698c1e2eaf6ebab147ab41a2dc49c8548a2264e1f7a515b8436

test:
  secret_key_base: 963feb366283e7db7e013e89cb069758925d4bf834d65a340f6d8dac593791c08faca2a54a538a40549eeb35a3535acf5d5ff0b9dd6f74efd3cc036765a8abb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
